// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
  [KeyType in keyof T]: T[KeyType];
};
/** Content for Homepage documents */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.TitleField;
  /**
   * rotatingStrings field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.rotatingstrings[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  rotatingstrings: prismicT.GroupField<
    Simplify<HomepageDocumentDataRotatingstringsItem>
  >;
  /**
   * NavigationItems field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.navigationItems[]
   * - **Tab**: NavigationBar
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  navigationItems: prismicT.GroupField<
    Simplify<HomepageDocumentDataNavigationItemsItem>
  >;
  /**
   * about_title field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.about_title
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  about_title: prismicT.RichTextField;
  /**
   * about_content field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.about_content
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  about_content: prismicT.RichTextField;
  /**
   * about_image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.about_image
   * - **Tab**: About
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  about_image: prismicT.ImageField<never>;
  /**
   * services field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.services[]
   * - **Tab**: Services
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  services: prismicT.GroupField<Simplify<HomepageDocumentDataServicesItem>>;
  /**
   * counters field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.counters[]
   * - **Tab**: Counters
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  counters: prismicT.GroupField<Simplify<HomepageDocumentDataCountersItem>>;
  /**
   * images field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.images[]
   * - **Tab**: Gallery
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  images: prismicT.GroupField<Simplify<HomepageDocumentDataImagesItem>>;
  /**
   * videos field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.videos[]
   * - **Tab**: Gallery
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  videos: prismicT.GroupField<Simplify<HomepageDocumentDataVideosItem>>;
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices5[]
   * - **Tab**: Gallery
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices5: prismicT.SliceZone<HomepageDocumentDataSlices5Slice>;
  /**
   * testimonials field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[]
   * - **Tab**: Testimonials
   * - **Documentation**: https://prismic.io/docs/core-concepts/group
   *
   */
  testimonials: prismicT.GroupField<
    Simplify<HomepageDocumentDataTestimonialsItem>
  >;
  /**
   * Map Label Text field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.map_label_text
   * - **Tab**: Map
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  map_label_text: prismicT.KeyTextField;
  /**
   * Label Link field in *Homepage*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.map_label_link
   * - **Tab**: Map
   * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
   *
   */
  map_label_link: prismicT.LinkField;
  /**
   * Map Lat field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.map_lat
   * - **Tab**: Map
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  map_lat: prismicT.NumberField;
  /**
   * lng field in *Homepage*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.map_lng
   * - **Tab**: Map
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  map_lng: prismicT.NumberField;
}
/**
 * Item in Homepage → rotatingStrings
 *
 */
export interface HomepageDocumentDataRotatingstringsItem {
  /**
   * text field in *Homepage → rotatingStrings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.rotatingstrings[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  text: prismicT.KeyTextField;
}
/**
 * Item in Homepage → NavigationItems
 *
 */
export interface HomepageDocumentDataNavigationItemsItem {
  /**
   * Name field in *Homepage → NavigationItems*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.navigationItems[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  name: prismicT.RichTextField;
}
/**
 * Item in Homepage → services
 *
 */
export interface HomepageDocumentDataServicesItem {
  /**
   * title field in *Homepage → services*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.services[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.TitleField;
  /**
   * content field in *Homepage → services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.services[].content
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  content: prismicT.RichTextField;
  /**
   * icon field in *Homepage → services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.services[].icon
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  icon: prismicT.ImageField<never>;
}
/**
 * Item in Homepage → counters
 *
 */
export interface HomepageDocumentDataCountersItem {
  /**
   * title field in *Homepage → counters*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.counters[].title
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  title: prismicT.RichTextField;
  /**
   * counter field in *Homepage → counters*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.counters[].counter
   * - **Documentation**: https://prismic.io/docs/core-concepts/number
   *
   */
  counter: prismicT.NumberField;
}
/**
 * Item in Homepage → images
 *
 */
export interface HomepageDocumentDataImagesItem {
  /**
   * image field in *Homepage → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.images[].image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
}
/**
 * Item in Homepage → videos
 *
 */
export interface HomepageDocumentDataVideosItem {
  /**
   * youtubeVideoId field in *Homepage → videos*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.videos[].youtubevideoid
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  youtubevideoid: prismicT.KeyTextField;
}
/**
 * Slice for *Homepage → Slice Zone*
 *
 */
type HomepageDocumentDataSlices5Slice = never;
/**
 * Item in Homepage → testimonials
 *
 */
export interface HomepageDocumentDataTestimonialsItem {
  /**
   * name field in *Homepage → testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].name
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  name: prismicT.KeyTextField;
  /**
   * text field in *Homepage → testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.testimonials[].text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismicT.RichTextField;
}
/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;
/** Content for post documents */
interface PostDocumentData {
  /**
   * title field in *post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  title: prismicT.KeyTextField;
  /**
   * Header Image field in *post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post.header_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  header_image: prismicT.ImageField<never>;
  /**
   * publish_date field in *post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: post.publish_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/date
   *
   */
  publish_date: prismicT.DateField;
  /**
   * Slice Zone field in *post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/core-concepts/slices
   *
   */
  slices: prismicT.SliceZone<PostDocumentDataSlicesSlice>;
}
/**
 * Slice for *post → Slice Zone*
 *
 */
type PostDocumentDataSlicesSlice =
  | ParagraphSlice
  | VideoSlice
  | ImageSlice
  | CenteredTextSlice;
/**
 * post document from Prismic
 *
 * - **API ID**: `post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostDocument<Lang extends string = string> =
  prismicT.PrismicDocumentWithUID<Simplify<PostDocumentData>, "post", Lang>;
export type AllDocumentTypes = HomepageDocument | PostDocument;
/**
 * Primary content in CenteredText → Primary
 *
 */
interface CenteredTextSliceDefaultPrimary {
  /**
   * text field in *CenteredText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_text.primary.text
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  text: prismicT.RichTextField;
}
/**
 * Default variation for CenteredText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CenteredTextSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<CenteredTextSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *CenteredText*
 *
 */
type CenteredTextSliceVariation = CenteredTextSliceDefault;
/**
 * CenteredText Shared Slice
 *
 * - **API ID**: `centered_text`
 * - **Description**: `CenteredText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type CenteredTextSlice = prismicT.SharedSlice<
  "centered_text",
  CenteredTextSliceVariation
>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceDefaultPrimary {
  /**
   * image field in *Image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * description field in *Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image.primary.description
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  description: prismicT.RichTextField;
}
/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<ImageSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Image*
 *
 */
type ImageSliceVariation = ImageSliceDefault;
/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSlice = prismicT.SharedSlice<"image", ImageSliceVariation>;
/**
 * Primary content in ImageWithCaption → Primary
 *
 */
interface ImageWithCaptionSliceDefaultSlicePrimary {
  /**
   * image field in *ImageWithCaption → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_caption.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * caption field in *ImageWithCaption → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_caption.primary.caption
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  caption: prismicT.RichTextField;
}
/**
 * Default slice variation for ImageWithCaption Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `ImageWithCaption`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageWithCaptionSliceDefaultSlice = prismicT.SharedSliceVariation<
  "default-slice",
  Simplify<ImageWithCaptionSliceDefaultSlicePrimary>,
  never
>;
/**
 * Primary content in ImageWithCaption → Primary
 *
 */
interface ImageWithCaptionSliceFullWidthImagePrimary {
  /**
   * image field in *ImageWithCaption → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_caption.primary.image
   * - **Documentation**: https://prismic.io/docs/core-concepts/image
   *
   */
  image: prismicT.ImageField<never>;
  /**
   * caption field in *ImageWithCaption → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_caption.primary.caption
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  caption: prismicT.RichTextField;
}
/**
 * Full Width Image variation for ImageWithCaption Slice
 *
 * - **API ID**: `fullWidthImage`
 * - **Description**: `ImageWithCaption`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageWithCaptionSliceFullWidthImage = prismicT.SharedSliceVariation<
  "fullWidthImage",
  Simplify<ImageWithCaptionSliceFullWidthImagePrimary>,
  never
>;
/**
 * Slice variation for *ImageWithCaption*
 *
 */
type ImageWithCaptionSliceVariation =
  | ImageWithCaptionSliceDefaultSlice
  | ImageWithCaptionSliceFullWidthImage;
/**
 * ImageWithCaption Shared Slice
 *
 * - **API ID**: `image_with_caption`
 * - **Description**: `ImageWithCaption`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageWithCaptionSlice = prismicT.SharedSlice<
  "image_with_caption",
  ImageWithCaptionSliceVariation
>;
/**
 * Item in Paragraph → Items
 *
 */
export interface ParagraphSliceDefaultItem {
  /**
   * paragraph field in *Paragraph → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: paragraph.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  paragraph: prismicT.RichTextField;
}
/**
 * Default variation for Paragraph Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ParagraphSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ParagraphSliceDefaultItem>
>;
/**
 * Slice variation for *Paragraph*
 *
 */
type ParagraphSliceVariation = ParagraphSliceDefault;
/**
 * Paragraph Shared Slice
 *
 * - **API ID**: `paragraph`
 * - **Description**: `Paragraph`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ParagraphSlice = prismicT.SharedSlice<
  "paragraph",
  ParagraphSliceVariation
>;
/**
 * Primary content in Quote → Primary
 *
 */
interface QuoteSliceDefaultSlicePrimary {
  /**
   * quote field in *Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote.primary.quote
   * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
   *
   */
  quote: prismicT.RichTextField;
}
/**
 * Default slice variation for Quote Slice
 *
 * - **API ID**: `default-slice`
 * - **Description**: `Quote`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuoteSliceDefaultSlice = prismicT.SharedSliceVariation<
  "default-slice",
  Simplify<QuoteSliceDefaultSlicePrimary>,
  never
>;
/**
 * Slice variation for *Quote*
 *
 */
type QuoteSliceVariation = QuoteSliceDefaultSlice;
/**
 * Quote Shared Slice
 *
 * - **API ID**: `quote`
 * - **Description**: `Quote`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type QuoteSlice = prismicT.SharedSlice<"quote", QuoteSliceVariation>;
/**
 * Primary content in Video → Primary
 *
 */
interface VideoSliceDefaultPrimary {
  /**
   * videoId field in *Video → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: video.primary.videoid
   * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
   *
   */
  videoid: prismicT.KeyTextField;
}
/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Default`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSliceDefault = prismicT.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;
/**
 * Slice variation for *Video*
 *
 */
type VideoSliceVariation = VideoSliceDefault;
/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: `Video`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type VideoSlice = prismicT.SharedSlice<"video", VideoSliceVariation>;
declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }
  namespace Content {
    export type {
      HomepageDocumentData,
      HomepageDocumentDataRotatingstringsItem,
      HomepageDocumentDataNavigationItemsItem,
      HomepageDocumentDataServicesItem,
      HomepageDocumentDataCountersItem,
      HomepageDocumentDataImagesItem,
      HomepageDocumentDataVideosItem,
      HomepageDocumentDataSlices5Slice,
      HomepageDocumentDataTestimonialsItem,
      HomepageDocument,
      PostDocumentData,
      PostDocumentDataSlicesSlice,
      PostDocument,
      AllDocumentTypes,
      CenteredTextSliceDefaultPrimary,
      CenteredTextSliceDefault,
      CenteredTextSliceVariation,
      CenteredTextSlice,
      ImageSliceDefaultPrimary,
      ImageSliceDefault,
      ImageSliceVariation,
      ImageSlice,
      ImageWithCaptionSliceDefaultSlicePrimary,
      ImageWithCaptionSliceDefaultSlice,
      ImageWithCaptionSliceFullWidthImagePrimary,
      ImageWithCaptionSliceFullWidthImage,
      ImageWithCaptionSliceVariation,
      ImageWithCaptionSlice,
      ParagraphSliceDefaultItem,
      ParagraphSliceDefault,
      ParagraphSliceVariation,
      ParagraphSlice,
      QuoteSliceDefaultSlicePrimary,
      QuoteSliceDefaultSlice,
      QuoteSliceVariation,
      QuoteSlice,
      VideoSliceDefaultPrimary,
      VideoSliceDefault,
      VideoSliceVariation,
      VideoSlice,
    };
  }
}
