// This file is generated by Slice Machine. Update with care!

import Image from './Image';
import Quote from './Quote';
import Text from './Text';

export {
	Image,
	Quote,
	Text,
};

export const components = {
	image: Image,
	quote: Quote,
	text: Text,
};
