// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  centered_text: dynamic(() => import("./CenteredText")),
  image: dynamic(() => import("./Image")),
  image_with_caption: dynamic(() => import("./ImageWithCaption")),
  paragraph: dynamic(() => import("./Paragraph")),
  quote: dynamic(() => import("./Quote")),
  video: dynamic(() => import("./Video")),
};
