blank_issues_enabled: false
contact_links:
  - name: 👪 Prismic Community Forum
    url: https://community.prismic.io
    about: Ask a question about the starter or raise an issue directly related to Prismic. You will usually get support there more quickly!
